const { formatInTimeZone } = require('date-fns-tz');

// Simulate a date generated by `eachDayOfInterval` in a timezone like UTC-11
// Local time 00:00 in UTC-11 is 11:00 UTC.
const d = new Date("2026-08-01T11:00:00Z"); 
console.log(formatInTimeZone(d, 'Asia/Jakarta', 'MMM dd'));
